import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Suspense } from "react";
import { Route, Routes } from "react-router-dom";
import { ConfirmDialog } from "primereact/confirmdialog";
import { ProtectedRoute } from "../auth/ProtectedRoute";
import { Sidebar } from "../components/Layout/Sidebar";
import { Topbar } from "../components/Layout/Topbar";
import { LoginPage } from "../features/auth/LoginPage";
import { DashboardPage } from "../features/dashboard/DashboardPage";
import { ClientesList } from "../features/clientes/ClientesList";
import { ClienteForm } from "../features/clientes/ClienteForm";
import { VehiculosList } from "../features/vehiculos/VehiculosList";
import { VehiculoForm } from "../features/vehiculos/VehiculoForm";
import { ProductosList } from "../features/inventario/ProductosList";
import { ProductoForm } from "../features/inventario/ProductoForm";
import { OTList } from "../features/otes/OTList";
import { OTForm } from "../features/otes/OTForm";
import { FacturasList } from "../features/facturacion/FacturasList";
import { FacturaDetail } from "../features/facturacion/FacturaDetail";
import { CalendarPage } from "../features/citas/CalendarPage";
import { UsuariosList } from "../features/usuarios/UsuariosList";
import { UsuarioForm } from "../features/usuarios/UsuarioForm";
import { ReportesPage } from "../features/reportes/ReportesPage";
const MainLayout = () => (_jsxs("div", { className: "app-layout", children: [_jsx(Sidebar, {}), _jsxs("div", { className: "main-content", children: [_jsx(Topbar, {}), _jsxs("main", { className: "page-wrapper", children: [_jsx(ConfirmDialog, {}), _jsx(Suspense, { fallback: _jsx("div", { children: "Cargando..." }), children: _jsxs(Routes, { children: [_jsx(Route, { index: true, element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "clientes", element: _jsx(ClientesList, {}) }), _jsx(Route, { path: "clientes/nuevo", element: _jsx(ClienteForm, {}) }), _jsx(Route, { path: "clientes/:id", element: _jsx(ClienteForm, {}) }), _jsx(Route, { path: "vehiculos", element: _jsx(VehiculosList, {}) }), _jsx(Route, { path: "vehiculos/nuevo", element: _jsx(VehiculoForm, {}) }), _jsx(Route, { path: "vehiculos/:id", element: _jsx(VehiculoForm, {}) }), _jsx(Route, { path: "inventario", element: _jsx(ProductosList, {}) }), _jsx(Route, { path: "inventario/nuevo", element: _jsx(ProductoForm, {}) }), _jsx(Route, { path: "inventario/:id", element: _jsx(ProductoForm, {}) }), _jsx(Route, { path: "otes", element: _jsx(OTList, {}) }), _jsx(Route, { path: "otes/nuevo", element: _jsx(OTForm, {}) }), _jsx(Route, { path: "otes/:id", element: _jsx(OTForm, {}) }), _jsx(Route, { path: "facturacion", element: _jsx(FacturasList, {}) }), _jsx(Route, { path: "facturacion/:id", element: _jsx(FacturaDetail, {}) }), _jsx(Route, { path: "citas", element: _jsx(CalendarPage, {}) }), _jsx(Route, { path: "reportes", element: _jsx(ReportesPage, {}) }), _jsx(Route, { path: "usuarios", element: _jsx(UsuariosList, {}) }), _jsx(Route, { path: "usuarios/nuevo", element: _jsx(UsuarioForm, {}) }), _jsx(Route, { path: "usuarios/:id", element: _jsx(UsuarioForm, {}) })] }) })] })] })] }));
export const AppRoutes = () => (_jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { element: _jsx(ProtectedRoute, {}), children: _jsx(Route, { path: "/*", element: _jsx(MainLayout, {}) }) })] }));
