version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: autotrack-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DB:-autotrack}
      MYSQL_USER: ${MYSQL_USER:-autotrack}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-autotrack_pwd}
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./backend
    container_name: autotrack-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend/.env
    environment:
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run python -m app.seeds.seed_data &&
             poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"

  web:
    build:
      context: ./frontend
    container_name: autotrack-web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
    ports:
      - "5173:5173"

volumes:
  db_data:

